### ISSUE TITLE
passing test that panics is treated as failed

### ISSUE THREAD

**Issue by marcelo-gonzalez** [near/nayduck#27]
Test run: https://nayduck.near.org/#/test/273186

[This test](https://github.com/near/nearcore/blob/6cbf26ddb281c875db446e72a6966790695f305c/integration-tests/src/tests/client/chunks_management.rs#L287) has #[should_panic] above it: ,

but it was treated as failed. Also note that the test output says

```
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 266 filtered out; finished in 5.10s
```

**Comment by mina86** [comment]
fd94e31802a2f9921d01740a753c7f1d10835db6 fixed this
