### ISSUE TITLE
Nayduck nightly build is broken

### ISSUE THREAD

**Issue by bowenwang1996** [near/nayduck#3]
Nightly build is broken. See http://nayduck.eastus.cloudapp.azure.com:3000/#/build/1469 for example

**Comment by mina86** [comment]
Looks like cargo is broken. This fails:
```
cargo build -j8 -p neard -p genesis-populate -p restaked \
            -p near-test-contracts --features adversarial \
            --features nightly_protocol,nightly_protocol_features
```
while this works:
```
cargo build -j8 -p neard --features adversarial \
            --features nightly_protocol,nightly_protocol_features
cargo build -j8 -p genesis-populate -p restaked -p near-test-contracts
```

**Comment by bowenwang1996** [comment]
@mina86 does that mean one of `genesis-populate`, `restaked`, and `near-test-contracts` cannot be built with nightly features? We should probably fix that

**Comment by mina86** [comment]
Those packages do not define those features. I’m pretty sure that running the two commands separately is a valid solution.

**Comment by mina86** [comment]
The above works for the listed packages but there’s also issue with:

```
cargo test --no-run --target-dir target_expensive -p near-client -p near-chunks -p neard -p near-chain --features=expensive_tests --features nightly_protocol --features nightly_protocol_features
```

Building all but the `near-client` works but then building just `near-client` fails:

```$ cargo test --no-run --target-dir target_expensive -p near-client --features=expensive_tests --features nightly_protocol --features nightly_protocol_features
   Compiling near-epoch-manager v0.0.1 (/home/mpn/code/near/nearcore/chain/epoch_manager)
   Compiling near-chunks v0.1.0 (/home/mpn/code/near/nearcore/chain/chunks)
error[E0574]: expected struct, variant or union type, found enum `BlockInfo`
   --> chain/epoch_manager/src/test_utils.rs:315:5
    |
315 |     BlockInfo {
    |     ^^^^^^^^^ not a struct, variant or union type
```

Part of the issue is https://github.com/rust-lang/cargo/issues/6915 which prevents features from selecting features on dev-dependencies.

**Comment by bowenwang1996** [comment]
@mina86 so maybe we should tackle https://github.com/near/nearcore/issues/4357 first
