### ISSUE TITLE
Fuzzer sometimes loses the reproducer file

### ISSUE THREAD

**Issue by Ekleog-NEAR** [near/nayduck#36]
For some reason, sometimes the fuzzer loses the reproducer file and it vanishes from the /datadrive of the nayduck worker that found it (probably after the next rsync).

We should:
1. Make the upload-to-gcs logic more resilient
2. As a fallback, send the reproducer as a zulip upload? (This would mean that zulip would then have the reproducer, while before we were safe behind the gcs auth… but then zulip already has other private discussions so the reproducer would probably not be the worst)

To see the issue:
- Subscribe to the pagoda/fuzzer/private zulip channel
- Observe that the last 3 crashes that were reported with `artifact crash-` in the thread title do not have a corresponding artifact on the near-nayduck GCS bucket (at the place the message says it should be)
- Observe that ssh’ing directly onto the machine listed at the top of the message, looking through `/datadrive/fuzz-corpus` for the artifact file, does not yield any result either
- Note that this machine does have logs, both in `/datadrive/fuzz-logs` and in `journald`, but I could not find anything that seemed relevant there

**Comment by Ekleog-NEAR** [comment]
The reproducer file is un-recoverable: it’s not on the hard disk of the nayduck machine that found it, and it’s not on the GCS bucket either. FWIW we’re currently discussing in contract-runtime how to improve on that, here’s an issue I just opened with the options moving forward: https://github.com/near/nayduck/issues/37

**Comment by Ekleog-NEAR** [comment]
For now, the last 3 times the fuzzer reported a bug, the reproducer was lost. However, with eg. one of the recent OOM issues, I am able to find reproducers. (But we don’t really care about OOM issues, as they’re most likely by-products of how the fuzzer runner works)

So I’d say we do miss actual issues, but still it’s not literally every time, it just so happened every time it mattered recently.

**Comment by vlad-kopcil** [comment]
more details in https://near.zulipchat.com/#narrow/stream/313811-pagoda.2Ffuzzer.2Fprivate

**Comment by akhi3030** [comment]
@vlad-kopcil, @nikurt: are there any updates on this issue please?

**Comment by vlad-kopcil** [comment]
Hi @akhi3030 I'm afraid that I still far from understanding how is the whole setup supposed to work. I had to finish some priority tasks within SRE team, and never worked with NayDuck before.
However, I take this as top priority from now on, and hope to have some break through this week.

**Comment by akhi3030** [comment]
Fingers crossed and thanks for the update @vlad-kopcil!
